DROP TABLE IF EXISTS users;

CREATE TABLE users (
  user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar NOT NULL,
  password varchar NOT NULL,
  firstname varchar NOT NULL,
  lastname varchar default NULL
);


INSERT INTO users (user_id,username,password,firstname,lastname) VALUES (1,'siva','siva','Siva Prasad Reddy','Katamreddy');
INSERT INTO users (user_id,username,password,firstname,lastname) VALUES (2,'admin','admin','Administrator','Mr');
INSERT INTO users (user_id,username,password,firstname,lastname) VALUES (3,'test','test','Guest','Mr');